# This rule is not used by the project cni-multi itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to multiapp.zlw.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cni-multi
    app.kubernetes.io/managed-by: kustomize
  name: backuppolicy-viewer-role
rules:
- apiGroups:
  - multiapp.zlw.domain
  resources:
  - backuppolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multiapp.zlw.domain
  resources:
  - backuppolicies/status
  verbs:
  - get
